### ISSUE TITLE
Unhandled Promise Rejections

### ISSUE THREAD

**Issue by nickcharles** [stovmascript/react-native-version#11]
Hey hey,

Just started using this, two errors pop up when I run this from the command line. Things look to be working despite the errors.

```
(node:76030) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'indexOf' of undefined
(node:76030) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Currently I've got it installed globally. Going to try to make it local to the package and see if that changes anything.

**EDIT**: Looks like having it installed as a local package hasn't changed anything.

**Comment by stovmascript** [comment]
@nickcharles Thanks for the report, will take a look into it later today.

**Comment by stovmascript** [comment]
Are you running Node v7 @nickcharles ? Seems like the first warning was introduced with Node v6 and the second one with v7. I only tested on v4. Will expand test environment to all LTS versions and the current stable version + fix this issue.

The package should be working fine though, looks like they're really only warnings.

**Comment by nickcharles** [comment]
Yeap I'm on v7.2.0, but you're right in that it looks like they are just warnings. They popped in and out with inconsistency so I am no longer sure that your package is actually causing them. Feel free to close this issue.
