### ISSUE TITLE
Suggestion: Parse/forward (agvtool) errors

### ISSUE THREAD

**Issue by skattyadz** [stovmascript/react-native-version#15]
Right now the project reports `There are no Xcode project files in this directory.  agvtool needs a project to operate.` when agvtool fails. In my case it was failing because I'd missed a setup step:

```
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
```

**Comment by stovmascript** [comment]
Hm, errors should definitely be forwarded. Looks like a bug. Thanks for reporting, will take a look.

**Comment by skattyadz** [comment]
No worries. Thanks for the prompt reply. Helpful project

**Comment by stovmascript** [comment]
Another issue with errors, that should've been forwarded: #22
