### ISSUE TITLE
Unable to resolve module `child_process`

### ISSUE THREAD

**Issue by RooneyJung** [stovmascript/react-native-version#17]
Unable to resolve module `child_process` in react-native-version/index.js
because RN doesn't support that.
(RN v0.42)

**Comment by stovmascript** [comment]
Hi @RooneyJung 

Can you please post how you're using react-native-version? It seems that you are using it inside your RN app. It would be great if you could provide some details, even code maybe?

**Comment by RooneyJung** [comment]
Hi.

Here are some informations.

react-native v0.42.0

npm v4.1.2

node v7.6.0 (I also tested v6.5.0)


dependencies in 'package.json'

"dependencies": {

    "react": "15.4.2",

    "react-native": "0.42.0",

    "react-native-drawer": "^2.3.0",

    "react-native-i18n": "^1.0.0",

    "react-native-vector-icons": "^4.0.0",

    "react-native-version": "^2.3.0",

    "react-redux": "^5.0.3",

    "redux": "^3.6.0",

    "redux-actions": "^2.0.1"

  },


In the source code, there are no specific lines.

I just added only one line.

*import { version } from 'react-native-version';*

Removing that line, no errors. Only the code makes errors.

And, at a console, If I command 'npm version <someversion>',
It also occurs errors.

-----

> react-native-version


[RNV] Versioning Android...

[RNV] Android updated

[RNV] Versioning iOS...

[RNV] iOS updated

[RNV] Amending...

fatal: Not a git repository (or any of the parent directories): .git
<-- yes, it's test project, so i don't use git.

[RNV] Done, with errors.


npm ERR! Darwin 16.4.0

npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm"
"version" "0.0.5"

npm ERR! node v7.6.0

npm ERR! npm  v4.1.2

npm ERR! code ELIFECYCLE

npm ERR! <My Project Name>@0.0.5 postversion: `react-native-version`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the <My Project Name>@0.0.5 postversion script
'react-native-version'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the <My Project
Name> package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     react-native-version

npm ERR! You can get information on how to open an issue for this project
with:

npm ERR!     npm bugs <My Project Name>

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls <My Project Name>

npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:

npm ERR!     <My Project Path>/npm-debug.log

-----


Before I created the issue, I found some posts like that.
https://github.com/facebook/react-native/issues/7170


Thank you! Good Luck :)


2017-03-20 17:46 GMT+09:00 Martin Šťovíček <notifications@github.com>:

**Comment by stovmascript** [comment]
RNV is not designed to be imported into your app code. It can be run from the command line, or you can import it into your custom script.

It's true that RNV depends on Git and maybe it should be mentioned somewhere...

**Comment by RooneyJung** [comment]
Thank you for reply.

Ok. I understood.
I just didn't know it, because in your README.md 'API' part seems to me
that it can be used in RN.

So, now I use RNV for npm, and also use react-native-version-name for RN.
They are very helpful for me.
Thank you again :)



2017-03-20 20:21 GMT+09:00 Martin Šťovíček <notifications@github.com>:

**Comment by stovmascript** [comment]
Np :) Glad you find it useful.

**Comment by JamesGs1994** [comment]
Can we use `child_process` as `react-native-childprocess` in React native project
