### ISSUE TITLE
husky, list-staged, not found

### ISSUE THREAD

**Issue by love8587** [stovmascript/react-native-version#173]
It's working well when I tried to command manually. 
```
npm version patch
./node_modules/react-native-version/cli.js
```

However, when I try to command using postversion huscky error occurs.

```
 ✘ npm version patch           
v0.1.22

> news-app@0.1.22 postversion /Users/bhbaek/Homestead/code/news-app
> node ./node_modules/react-native-version/cli.js

[RNV] Versioning Android...
[RNV] Android updated
[RNV] Versioning iOS...
[RNV] iOS updated
[RNV] Amending...
husky > pre-commit (node v10.16.0)
zsh:1: command not found: lint-staged
husky > pre-commit hook failed (add --no-verify to bypass)
Can't find Husky, skipping pre-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
[RNV] Adjusting Git tag...
[RNV] Done
```

What should I do to address it?

**Comment by stovmascript** [comment]
This looks like an issue with your project setup. Can you paste your package.json? Is the `npm version patch` command being run on some CI service?

**Comment by love8587** [comment]
@stovmascript Yes, it was being on CI server (Bitbucket Pipeline). I resolved it with another approach. 

This is my solution; 
https://gist.github.com/love8587/2272c7b241ab99fe88cd797de593f6b0

**Comment by stovmascript** [comment]
@love8587 Ok, so it works?

This usually is some problem with deps not being installed or another node binary is being executed and its working directory is not in your project folder.

**Comment by love8587** [comment]
@stovmascript Yes, it works. I will send full script If you would like to get full of package.json.

**Comment by stovmascript** [comment]
It looks like it's not a bug with library, so I don't know what we could improve here.

From what I can see, you're running react-native-version manually via an npm script as a workaround, which is ok. To fix the "automatic" method, we would have to figure out what seems to be an environment issue during `postinstall` in your Bitbucket pipeline.
