### ISSUE TITLE
Version with prerelease tag "x.x.x-x" is working for android but not for ios

### ISSUE THREAD

**Issue by ThomasCarca** [stovmascript/react-native-version#178]
Hello,

I'm trying to use react-native-version to propagate the version 0.3.0-0 to both android and ios. It works fine for android but ios checks version 0.3.0 which is unwanted.

`yarn version --preminor` changes package.json to the following : 
![image](https://user-images.githubusercontent.com/24562239/76602012-606c2580-650a-11ea-94b6-42b198fe2bd0.png)

`npx react-native-version` changes the build.gradle to the following : 
![image](https://user-images.githubusercontent.com/24562239/76601990-534f3680-650a-11ea-87e7-267319a6fcc9.png)

... and info.plist to the following :
![image](https://user-images.githubusercontent.com/24562239/76602068-7e398a80-650a-11ea-8f0d-198b1acdda85.png)

**Expected behavior :**
info.plist should be updated to have version 0.3.0-0

Thank you !

**Comment by stovmascript** [comment]
Hi @ThomasCarca, unfortunately this is on purpose, please read #41. Apple won't allow a TestFlight/App Store release with a `x.x.x-x` format, only `x.x.x`. Sorry for this, but for now it seems to be out of our hands.

I will add some info to the README about this.
