### ISSUE TITLE
Incorrect git tag selected

### ISSUE THREAD

**Issue by nicinabox** [stovmascript/react-native-version#18]
I was investigating a similar issue I was having to https://github.com/stovmascript/react-native-version/issues/8 and I noticed a small problem when the git tag is amended (https://github.com/stovmascript/react-native-version/blob/master/index.js#L252).

`git tag | tail -1 ` returns the last tag, but not in ref order. For example:

```
$ git tag
v0.1.0
v0.10.0
v0.10.1
v0.2.0
v0.3.0
v0.4.0
v0.5.0
v0.6.0
v0.7.0
v0.7.1
v0.7.2
v0.8.0
v0.9.0
```

`git tag | tail -1 ` returns `v0.9.0`, but the last tag is actually `v0.10.1`. Specifying the sort order gives the right tag:

```
git tag --sort=v:refname | tail -1
```

**Comment by stovmascript** [comment]
Thanks for the PR and nice catch!
