### ISSUE TITLE
[Question] Allow iOS version update without OSX only tools ?

### ISSUE THREAD

**Issue by raphaelvigee** [stovmascript/react-native-version#21]
I'm a Linux user, updating version requires me to start a VM just for a simple version upgrade.

Is there any existing way to drop the `xcode-select` dependency ?

I just looked quickly at these there libraries:
- https://github.com/apache/cordova-node-xcode
- https://github.com/mgcrea/node-plist-native
- https://github.com/bberthelemy/xcode-node

I'm pretty sure they can handle the iOS file updating job, as a fallback of `avgtools`

With less dependencies, an approach similar to the Android one can be used to patch the `project.pbxproj` file and the `node-plist-native` can take care of the different `Info.plist` files.

**Comment by stovmascript** [comment]
I considered using node-xcode or a plist parser at the start of the project, but in the end opted for `avgtools` so I could plow through and because they take care of everything (multiple project files and plists) with one command.

Seeing as it's needed now, it would be appropriate to take a look at it again and free us from the macOS dependency.

Only problem is that I'll be free to work on this in mid-June. So in the meantime, I'll accept a PR, if you want to take a stab at it @raphaelvigee. That would be great.

**Comment by stovmascript** [comment]
We could actually pull out `avgtools` altogether and get rid of #15.

**Comment by raphaelvigee** [comment]
I have a busy schedule at the moment, I'll try to give it a try.

Do you consider dropping completly the `xcode` dependency or adding a fallback ?

**Comment by stovmascript** [comment]
I think that if we recreate the behaviour we have right now with `agvtool`, we will cover more platforms including macOS, so I don't think a fallback would be needed. There's also some checks for the Xcode CLI tools, which could then be removed.

The only downside is that as Xcode and React Native evolve, we might have to adjust things more than just updating the docs to account for some new thing that RN or Xcode require.

**Comment by raphaelvigee** [comment]
Yes of course, some maintenance work would be necessary, that's why I was thinking about keeping the `xcode` behavior and give the user a choice

**Comment by stovmascript** [comment]
Yeah, sounds reasonable. Perhaps some `-L, --legacy` switch à la [nodemon](https://github.com/remy/nodemon#application-isnt-restarting).

**Comment by ujwal-setlur** [comment]
any update on this? Thanks.

**Comment by stovmascript** [comment]
Hey @ujwal-setlur, I've been swamped recently, but might be able to squeeze some time in this weekend and finally start working on it.

**Comment by ujwal-setlur** [comment]
Hey @stovmascript, thanks! In the meantime, I wrote a tiny CLI utility jsplist to manipulate plist files. Not sure if this will be useful for you here, but you are welcome to look at it. 

https://github.com/ujwal-setlur/jsplist/blob/master/README.md

**Comment by stovmascript** [comment]
So I started working on it. Xcode parsing is done. Now working on updating plists, which is the easy part. Unfortunately, all of the plist parsing utils out there right now can't pretty print the file back out with a custom or original indentation, which makes for bad diffs.

**Comment by ujwal-setlur** [comment]
I would imagine most of it would be whitespaces, right? Most diff utils can handle that with the appropriate flag, I would think. Or some combination of diff and tr.

**Comment by stovmascript** [comment]
The plists RN comes with are indented with tabs, same indentation done by `plutil` of the Xcode toolchain. On top of that it doesn't indent the first `<dict>` tag. I know it's a detail and all, but I it's a pain doing manual upgrades of RN to notice changes in a simple `git diff` because the indentation kept changing.

**Comment by allyburns** [comment]
@stovmascript - Thank you for working on a version that doesn't rely on OSX only tools. I just discovered this package today and want to add it to our workflow, which will be possible once you finish cracking this Issue, thanks for finding the time.

**Comment by stovmascript** [comment]
@allyburns I'm actually just just finalizing the work right now. Should be released momentarily.

**Comment by stovmascript** [comment]
@raphaelvigee @ujwal-setlur @allyburns Alright guys, new version (2.4.0) is out now on [npm](https://www.npmjs.com/package/react-native-version), free of the macOS/Xcode dependency by default.

If you're on a Mac and need or want to use the native `agvtool` method, add the `-L, --legacy` option to your command.
