### ISSUE TITLE
CFBundleShortVersionString not being updated on main plist

### ISSUE THREAD

**Issue by wachunei** [stovmascript/react-native-version#22]
I may have set project incorrectly, but when doing `npm version <someVersion>`, `postversion` runs and updates gradle file and tv-OS/Test `Info.plist` files, with corresponding build and `CFBundleShortVersionString`, but in my main `Info.plist` only gets build number bumped and `CFBundleShortVersionString` remains the same as before using this package.

Any ideas? Thanks.

**Comment by wachunei** [comment]
Here's the `diff patch` after running `npm version`, you can see `ios/InternetUC/Info.plist` was not updated, am I doing anything wrong?

```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 8c9d419..42cffce 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -90,8 +90,8 @@ android {
         applicationId "com.internetuc"
         minSdkVersion 16
         targetSdkVersion 22
-        versionCode 6
-        versionName "1.1.2"
+        versionCode 7
+        versionName "1.1.3"
         ndk {
             abiFilters "armeabi-v7a", "x86"
         }
diff --git a/ios/InternetUC-tvOS/Info.plist b/ios/InternetUC-tvOS/Info.plist
index 2fb6a11..a78dfde 100644
--- a/ios/InternetUC-tvOS/Info.plist
+++ b/ios/InternetUC-tvOS/Info.plist
@@ -15,11 +15,11 @@
 	<key>CFBundlePackageType</key>
 	<string>APPL</string>
 	<key>CFBundleShortVersionString</key>
-	<string>1.0</string>
+	<string>1.1.3</string>
 	<key>CFBundleSignature</key>
 	<string>????</string>
 	<key>CFBundleVersion</key>
-	<string>1</string>
+	<string>6</string>
 	<key>LSRequiresIPhoneOS</key>
 	<true/>
 	<key>UILaunchStoryboardName</key>
diff --git a/ios/InternetUC-tvOSTests/Info.plist b/ios/InternetUC-tvOSTests/Info.plist
index 886825c..9b15f53 100644
--- a/ios/InternetUC-tvOSTests/Info.plist
+++ b/ios/InternetUC-tvOSTests/Info.plist
@@ -15,10 +15,10 @@
 	<key>CFBundlePackageType</key>
 	<string>BNDL</string>
 	<key>CFBundleShortVersionString</key>
-	<string>1.0</string>
+	<string>1.1.3</string>
 	<key>CFBundleSignature</key>
 	<string>????</string>
 	<key>CFBundleVersion</key>
-	<string>1</string>
+	<string>6</string>
 </dict>
 </plist>
diff --git a/ios/InternetUC.xcodeproj/project.pbxproj b/ios/InternetUC.xcodeproj/project.pbxproj
index bdc02c5..4e4318b 100644
--- a/ios/InternetUC.xcodeproj/project.pbxproj
+++ b/ios/InternetUC.xcodeproj/project.pbxproj
@@ -1186,7 +1186,7 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-				CURRENT_PROJECT_VERSION = 5;
+				CURRENT_PROJECT_VERSION = 6;
 				DEAD_CODE_STRIPPING = NO;
 				DEVELOPMENT_TEAM = L388Z72LTH;
 				HEADER_SEARCH_PATHS = (
@@ -1210,7 +1210,7 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-				CURRENT_PROJECT_VERSION = 5;
+				CURRENT_PROJECT_VERSION = 6;
 				DEVELOPMENT_TEAM = L388Z72LTH;
 				HEADER_SEARCH_PATHS = (
 					"$(inherited)",
diff --git a/ios/InternetUCTests/Info.plist b/ios/InternetUCTests/Info.plist
index 886825c..9b15f53 100644
--- a/ios/InternetUCTests/Info.plist
+++ b/ios/InternetUCTests/Info.plist
@@ -15,10 +15,10 @@
 	<key>CFBundlePackageType</key>
 	<string>BNDL</string>
 	<key>CFBundleShortVersionString</key>
-	<string>1.0</string>
+	<string>1.1.3</string>
 	<key>CFBundleSignature</key>
 	<string>????</string>
 	<key>CFBundleVersion</key>
-	<string>1</string>
+	<string>6</string>
 </dict>
 </plist>
```

**Comment by stovmascript** [comment]
I've just tried on a brand new RN project and also updated the tests and RN version being tested to accommodate for tvOS, but it seems to be working without altering the source of RNV.

Could you post some version details? node & npm/yarn, Xcode, RN...

**Comment by wachunei** [comment]
Sure.

```sh
$ node --version; npm --version; yarn --version; react-native --version; /usr/bin/xcodebuild -version

v8.0.0
5.0.1
0.24.6
react-native-cli: 2.0.1
react-native: 0.44.2
Xcode 8.3.2
Build version 8E2002
```

I'm working on [this open sourced repo](https://github.com/wachunei/internetuc-react-native) btw, I've set build number to 5 (the current), add `"postversion": "react-native-version --never-amend"` and run `npm version 1.1.3`.

What is more intriguing to me is that it has effectively changed some of the plist but not all of them.

**Comment by stovmascript** [comment]
So I ran `agvtool` (which handles the iOS versioning part for RNV) by itself on your repo to see what would happen:

```
internetuc-react-native $ cd ios/
ios $ agvtool new-marketing-version 1.1.3
Setting CFBundleShortVersionString of project InternetUC to: 
    1.1.3.

Updating CFBundleShortVersionString in Info.plist(s)...

$(SRCROOT)/InternetUC/Info.plist
Cannot find "$(SRCROOT)/InternetUC/Info.plist"
Updated CFBundleShortVersionString in "InternetUC.xcodeproj/../InternetUC-tvOS/Info.plist" to 1.1.3
Updated CFBundleShortVersionString in "InternetUC.xcodeproj/../InternetUC-tvOSTests/Info.plist" to 1.1.3
Updated CFBundleShortVersionString in "InternetUC.xcodeproj/../InternetUCTests/Info.plist" to 1.1.3
```

And it looks like your Xcode project is misconfigured at these two lines:

- https://github.com/wachunei/internetuc-react-native/blob/develop/ios/InternetUC.xcodeproj/project.pbxproj#L1196
- https://github.com/wachunei/internetuc-react-native/blob/develop/ios/InternetUC.xcodeproj/project.pbxproj#L1219

Removing `$(SRCROOT)/` here solves the issue: ![screenshot 2017-06-02 15 23 36](https://cloud.githubusercontent.com/assets/14262802/26727679/f2f096b2-47a7-11e7-85b7-5faceb2e2d8d.png)

Do you have the absolute path there for a specific reason?

**Comment by wachunei** [comment]
Thank you for taking some of your time to check this.

Actually I don't really know why it was set like that, [but I know it was done after renaming whole project](https://github.com/wachunei/internetuc-react-native/commit/98a587d0e06e8c2e8d989de511bbf045743733a4#diff-05a76e16670f63a69bae4f2dd10fbf80R1118)

I will now try to upgrade packages and bump version, then I'll close this issue later.

Thank you again!
