### ISSUE TITLE
Issue with SRCROOT not found therefore CFBundleNumber is not updated when avgtool is run

### ISSUE THREAD

**Issue by pencilcheck** [stovmascript/react-native-version#24]
https://github.com/facebook/react-native/issues/879

Is it possible if react-native-version can fix this? I don't know why the default ios project generated has this issue.

**Comment by stovmascript** [comment]
I don't think we should. It's a misconfiguration issue that can be easily fixed on existing projects and won't happen on new projects if RN fixes their Xcode template.

Btw, for anyone having trouble with this, here's how to fix it in your Xcode project: https://github.com/stovmascript/react-native-version/issues/22#issuecomment-305787460
