### ISSUE TITLE
Just to verify: there is NO option to NOT let the tool commit into git?

### ISSUE THREAD

**Issue by flq** [stovmascript/react-native-version#242]
Hi,
our plan was to run this tool in the Build pipeline - bump up version, perform build, make available for testers, etc. - we don't need the git committing and tagging. Right now it even actively breaks the build as git isn't properly configured. Also, imagine that a user of this tool does not actually use git but hg.

I looked through the options but don't seem to be able to completely turn off the committing behavior. Is there a way I don't know of?

**Comment by stovmascript** [comment]
Hi. We should try to improve these scenarios in the future. For now, to skip committing/tagging/amending you can run:

```bash
$ npm --no-git-tag-version version <newversion>
$ react-native-version --never-amend
```

You can also set `--never-amend` in the `postversion` npm script (see README).

**Comment by flq** [comment]
Right, thanks for clarifying :)
