### ISSUE TITLE
Support iOS Extensions target

### ISSUE THREAD

**Issue by HugoGresse** [stovmascript/react-native-version#307]
When an extension is pushed to the store on iOS, it should have the same bundle version as the main target, resulting in a warning on upload. 
It would be nice if this package would also update the extension version. 
More info on the extension [here](https://stackoverflow.com/questions/27953643/ios-extension-is-it-necessary-to-increment-its-bundle-version-cfbundleversion)

**Comment by hosseintalebi** [comment]
@HugoGresse when running `react-native-version`, it updates the version on both the extension and the containing app.

**Comment by HugoGresse** [comment]
You're right, sorry for this issue.
