### ISSUE TITLE
Default (i.e. non-legacy) versioning causing error

### ISSUE THREAD

**Issue by blakek** [stovmascript/react-native-version#32]
@stovmascript
First, thanks for this.  It's a great project.

For me, the legacy option correctly versions the Xcode project, but the default does not finish running.
I do not have an android folder in my project, and I'm running `react-native-version --target ios`

Currently, it just logs the following:

```
[RNV] Versioning iOS...
[RNV] undefined
```

...followed by the usage output.

I'm running through the source to see if I can give anything more helpful.  From briefly scanning the source, I tried running this:

```shell
RNV_ENV='ava' react-native-version --target ios
```
and I get `TypeError: errGrp.map is not a function`, which seems to refer to [`index.js:356`](https://github.com/stovmascript/react-native-version/blob/51b7c6fd4781777790c19f6c3a84505c0b35092d/index.js#L356)

**Comment by blakek** [comment]
Update: 🙈 the original problem came from the project name in the package.json not exactly matching the *.xcodeproj filename.  The package.json had a dash in the name while the Xcode project file didn't.

Would searching for any *.xcodeproj files in the specified ios folder be an accepted solution (I will be happy to submit a PR when I get time)?  Or should there be another option to specify not just the ios folder but the ios project folder?

Also, the error logging for that area could be fixed.  It seems like it expects an array of arrays but was given an array of Errors?  Again, if I get time, I can look into that more, too.

Thanks for your time and the awesome project!

**Comment by stovmascript** [comment]
@blakek Thanks, glad you find it useful.

Yeah, logging will need to be revised at some point. I'd like to use some basic CLI logging lib, if it won't be too much hassle to implement.

Thanks for submitting the PR, lets continue there on the topic of the Xcode filename...

**Comment by stovmascript** [comment]
@blakek New version (2.4.1) is out now on [npm](https://www.npmjs.com/package/react-native-version).
