### ISSUE TITLE
Add "--set-build" option

### ISSUE THREAD

**Issue by stovmascript** [stovmascript/react-native-version#37]
New option `-s, --set-build <number>` as described in #26.

**Comment by bdrobinson** [comment]
This would be really useful for me as my CI server takes care of incrementing the build number, so I don't need `react-native-version` to do it.

**Comment by stovmascript** [comment]
@bdrobinson So if I understand correctly, you have the next build number value available in your CI pipeline and you would use this option to set it to the same value that has already been set by some previous step?

**Comment by bdrobinson** [comment]
My plan was that using `--set-build` I could use `react-native-version --set-build 1` every time, since I always want the build number to be checked into git as 1.

And yes, definitely – a flag to completely disable incrementing the build number would work even better.

**Comment by jonoirwinrsa** [comment]
An alternative is to have your CI bump the versionCode in your android manifest. Just leave the versionCode field out of the build.gradle and this should still work

**Comment by etayluz** [comment]
We're using BitRise and it would be nice to set the Build Number and Patch Number to BitRise's Build Number so all three match.

**Comment by etayluz** [comment]
So is this happening? We need this.

**Comment by jonoirwinrsa** [comment]
@etayluz what problem are you having? What is the patch number? 

You can set the version code and version name using Bitrise's set-android-manifest-version step and there is a similar one for ios

**Comment by etayluz** [comment]
@jonoirwinrsa there is NO similar for iOS.

The problem we're having is that we want to set our build number to that of BitRise's. Currently, react-native-version only support auto-incrementation of the build as opposed to being able to set it to any integer of our choosing.

**Comment by jonoirwinrsa** [comment]
@etayluz how hard did you look for a similar step?

https://github.com/bitrise-io/steps-set-xcode-build-number

**Comment by etayluz** [comment]
@jonoirwinrsa admittedly not very hard :)

But we are a running a react native project and so we prefer to use this module instead of a platform specific step.

**Comment by jonoirwinrsa** [comment]
@etayluz are you building both Android and iOS on the same stack? I have never tried to build android on their XCode stack but it has been my assumption that you would need to install android tooling to get it to work.
If you are using the same stack and a single workflow you could run both steps - one after the other..

**Comment by Swingline0** [comment]
Was digging around for a similar answer here as I couldn't seem to find the Android equivalent in Bitrise for setting the version code (as the "steps-set-xcode-build-number" step does)...

After exploring some other routes, for some reason I was then able to find this step in the search:

![image](https://user-images.githubusercontent.com/1479206/38086367-0fbe44a4-3322-11e8-9a25-ce82f2fcd98d.png)

https://github.com/bitrise-community/steps-change-android-versioncode-and-versionname

Not sure why it wasn't coming up for me before but it's there now, so... woohoo...  testing now.

**Comment by stovmascript** [comment]
Hey guys, check out the new `--set-build` and `--never-increment-build` (@bdrobinson) options in the new version (2.5.0) that's out now on [npm](https://www.npmjs.com/package/react-native-version).
