### ISSUE TITLE
Android not bomping versionName.

### ISSUE THREAD

**Issue by DanGDroid** [stovmascript/react-native-version#39]
Hi,
I am using RN 0.45
"react-native-version": "^2.3.1"
and running a Fastlane script with incrementing build num on ios and android
ios is fine
android changes only versionCode but not versionName (from 0.0.1 or 0.1) it stays the same.
from 0.99 it bumps to 0.1 but no more

this is my script:
```shell
#!/usr/bin/env bash -e

./node_modules/.bin/react-native-version --target android --never-amend  ./

PROJECT_DIR="android/app"
GRADLE_FILE="build.gradle"
GRADLE_PATH="${PROJECT_DIR}/${GRADLE_FILE}"

PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')

SOURCE_BUILD_NUMBER=$(cat ${GRADLE_PATH} | grep versionCode | head -1 | sed -n 's/[[:space:]]*versionCode \([0-9]*\)$/\1/p')
BUILD_NUMBER=$(($SOURCE_BUILD_NUMBER))
echo Source build number: ${SOURCE_BUILD_NUMBER}, calculated build number: ${BUILD_NUMBER}
FULL_VERSION=${PACKAGE_VERSION}.${BUILD_NUMBER}

git commit -am "android_${FULL_VERSION} auto_commit"

echo Android full version: ${FULL_VERSION}

```

please help

**Comment by stovmascript** [comment]
Hey @DanGDroid, I tried your script. The problem is that you're not changing your `package.json` version prior to using RNV. RNV itself doesn't do any versioning, except for incrementing build numbers. You should use `npm version` somewhere in your script, or Fastlane before executing `react-native-version`.

**Comment by DanGDroid** [comment]
@stovmascript 
thanx for replying,
but if i use `npm version` it bumps the android and ios build numbers the same as `react-native-version` does - ending up with bumping twice (except of packeversion and thus android `versionName`)
any solution?

**Comment by stovmascript** [comment]
`npm version` doesn't touch your Android and iOS code, it only updates your `package.json` version key. `react-native-version` then takes this new value and updates your code in `android/` and `ios/`.

If you don't bump your `package.json` version, `versionName` will not be changed.

**Comment by DanGDroid** [comment]
i executed `npm version patch` on shell in my RN project and `packge.json` version bumpt,
and Android `build.gradle` `versionCode` was bumpt, and IOS `info.plist` `CFBundleVersion` was bumpt as well.
without using `react-native-version`
probably i'm missing something.

**Comment by stovmascript** [comment]
Have you by any chance set up the [`postversion` npm-script](https://github.com/stovmascript/react-native-version#npm-scripts-hook-automatic-method)? That's the only way I can think of for those values to be updated automatically.

**Comment by DanGDroid** [comment]
`postversion` was set by `react-native-version`,
this is in my `package.json`:
```javascript
"postversion": "react-native-version",
"build-android": "react-native-version --target android --never-amend && cd android/ && fastlane beta"
```

**Comment by stovmascript** [comment]
RNV only reads your `package.json`, so you must have added that yourself. If you remove the "postversion" script, your custom script should work as expected.

**Comment by DanGDroid** [comment]
👍 
that was it - an extra `postversion`, i removed it and excect. `npm version patch` and after that
`react-native-version` and all results as expected.
thanx mate.
