### ISSUE TITLE
Error : Unable to resolve module `child_process`

### ISSUE THREAD

**Issue by bhakta0007** [stovmascript/react-native-version#55]
"react": "16.2.0",
"react-native": "0.53.3",
"react-native-version": "^2.6.1",

I get a red screen in IOS simulator with this error:

error: bundling failed: Error: Unable to resolve module `child_process` from `/Users/bhakta/dev/F/drprax/node_modules/react-native-version/index.js`: Module does not exist in the module map

**Comment by stovmascript** [comment]
@bhakta0007 Hey, looks like you're importing this module into your app code. This module is meant for versioning your app in your Git project.

**Comment by bhakta0007** [comment]
I saw an example usage on the site and I thought I could use the module to read the versions back into the code.

https://www.npmjs.com/package/react-native-version#api

**Comment by stovmascript** [comment]
That API is for developers who need to version their app as part of their own script. It only sets version/build numbers.

To display the app version inside your app to your users, you'll need something like: https://www.npmjs.com/package/react-native-version-number

**Comment by bhakta0007** [comment]
Yes, I am now using react-native-version-number.

It would help if the README can clarify this point about the package.
