### ISSUE TITLE
postversion with yarn does not work as expected

### ISSUE THREAD

**Issue by suside** [stovmascript/react-native-version#58]
When you add
`"postversion": "react-native-version"`
and run 
`npm version --new-version patch`
you will end up with latest tag and HEAD having fallowing files updated:
```
 android/app/build.gradle      | 4 ++--
 ios/MyProject/Info.plist      | 6 +++---
 ios/MyProjectTests/Info.plist | 4 ++--
 package.json                  | 2 +-
```
and that is the expected behavior.

But when you do the same with
`yarn version --new-version patch`
your tag will have only:
```
 package.json | 2 +-
```
(with HEAD being ok)

I figured out that this happens because `yarn` is setting
`process.env.npm_config_version_git_tag`
instead
`process.env.npm_config_git_tag_version`
which is then read here:
https://github.com/stovmascript/react-native-version/blob/0642d25f6af7c49e97e973b825148f6c5823a7c7/index.js#L500-L502

I'm not sure if `yarn` is officially supported but the workaround is to use:
`"postversion": "react-native-version --amend"`
it should work with both `npm` and `yarn`

**Comment by stovmascript** [comment]
Whoa, nice find! Is it possible that this variable name was also changed in some new version of npm, or is it really yarn only?

**Comment by suside** [comment]
Not sure, I was testing inside project with
```
$ npm --version
6.0.1
$ yarn --version
1.6.0
```
and husky precommit enabled.
I will report back as soon as I figure out who and where exactly is setting those env's.

**Comment by suside** [comment]
Right, another `||` will definitely do the job.
But since workaround works I'm going to figure out what's going on underneath before doing any PRs.

**Comment by leethree** [comment]
I'm seeing the same problem and @suside 's workaround works. Would be great if it can be fixed.

**Comment by suside** [comment]
So it seems they do have different names
https://github.com/yarnpkg/yarn/blob/master/src/registries/yarn-registry.js#L17
vs
https://github.com/npm/cli/blob/latest/lib/config/defaults.js#L150
I'm not sure why.

It seems that another `||` would be the best solution indeed.
