### ISSUE TITLE
Not updating build.gradle versionName if existing value uses single quotes

### ISSUE THREAD

**Issue by Leeds-eBooks** [stovmascript/react-native-version#61]
Description is all in the title! `build.gradle` is a groovy file, and so both [single](http://groovy-lang.org/syntax.html#_single_quoted_string) and [double](http://groovy-lang.org/syntax.html#_double_quoted_string) quotes can be used. if your `build.gradle` has `versionName` defined with single quotes, it fails to update.

Thanks!

**Comment by stovmascript** [comment]
Thanks for reporting. Looks like an easy fix here: https://github.com/stovmascript/react-native-version/blob/0642d25f6af7c49e97e973b825148f6c5823a7c7/index.js#L180-L181

Will look into it later, or you're welcome to submit a PR... Just let me know.
