### ISSUE TITLE
Old plist version (possible low severity security issue)

### ISSUE THREAD

**Issue by joh-klein** [stovmascript/react-native-version#69]
The plist package, versions >=1.2.0 <3.0.1 is affected by a low severity ReDoS vulnerability:

https://app.snyk.io/vuln/npm:plist:20180219

**Comment by stovmascript** [comment]
@joh-klein Thanks for reporting this. I'll setup Greenkeeper (#70) and hopefully prevent issues like this in the future.

**Comment by stovmascript** [comment]
A new version of RNV (2.6.7) with updated dependencies (including plist 3.0.1) is now available on [npm](https://www.npmjs.com/package/react-native-version).
