### ISSUE TITLE
Amending the commit breaks git tag

### ISSUE THREAD

**Issue by parshap** [stovmascript/react-native-version#8]
Hi! Thanks for this package. It's a great way to use the `npm version` workflow with react-native apps.

I have an issue with the git tags created by `npm version`. It seems like once `react-native-version` amends the version commit, it doesn't also update the tag to point to the new tag. This results in the git tag pointing to the old commit that only has a `package.json` change and not the iOS and Android version changes.

**Comment by stovmascript** [comment]
Nice catch @parshap I'll take a look into it.

**Comment by chase-seibert** [comment]
I worked around this by switching from `postversion` to `version`, which executes BEFORE the `npm version` tag changes are committed:

```
  "scripts": {
    "version": "react-native-version --never-amend; git add ."
  },
```

**Comment by stovmascript** [comment]
@chase-seibert Cool! I assumed that during preversion/version the package.json (where RNV grabs the new version) isn't edited yet.

Think I'll open it up for all the npm version scripts and properly handle git tags in postversion - probably even make an option to disable fixing/amending git tags incase somebody explicitly wants their git tags to point the the original npm commit.
