### ISSUE TITLE
fatal: not a git repository....

### ISSUE THREAD

**Issue by flashman2** [stovmascript/react-native-version#98]
Running react-native-version --never-amend I got the following error: fatal: not a git repository (or any of the parent directories): .git

I'm not using my project's directory as a git repo, so I don't want this package to update my git repo. Is there any way to disable this option? It seems a long-lasting problem and not fixed for last few months.

**Comment by stovmascript** [comment]
@flashman2 You're right. RNV is going to need a tighter integration of npm client versioning features in the future.

In the meantime, I've updated the `--never-amend` option to not require Git, as it makes sense anyway. It's available now in the latest version (v3.1.0).
